---
dependency:
  name: galaxy
driver:
  name: podman
lint: | 
  yamllint .
  ansible-lint .

platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /sbin/init
  - name: instance1
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /sbin/init
  - name: instance2
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible