dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
